project:
  name: "ETL-Climate-Insight"

paths:
  raw_data_dir: "raw_data"
  data_dir: "data"
  jakarta_csv: "data_jakarta.csv"
  klhk_csv: "data_klhk.csv"
  aggregated_csv: "v_jakarta_trend_bulanan.csv"

database:
  sqlite:
    file_name: "climate_data.sqlite"
    table_name: "fact_sampah_harian"